# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Apex Coaching
email: craig@apexcoaching.co.za
# description: >- # this means to ignore newlines until "baseurl:"
# Bachelor of Business Admin. Honours (IMM)
# Foundations of Executive Coaching (UCT)
# Neuro Leadership Institute (NLI) Brain Based Coach
# Comensa Member
baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
linkedin_username: craig-stuart-ab244950

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# theme: jekyll-theme-basically-basic

# generate social links in footer
minima:
  social_links:
    linkedin: craig-stuart-ab244950
    # twitter: jekyllrb
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: xxx
    # flickr:   jekyll
    # instagram: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll
# These are default values for the frontmatter
# default:
#   - scope:
#       path: ""
#       type: "post"
#     values:
#         layout: "post"
#         title: "My Title"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

